In [16]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [6]:
df = pd.read_csv('homeprices.csv')
df.head(3)

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000

In [12]:
dummies = pd.get_dummies(df.town)
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [46]:
final = pd.concat([df ,dummies],axis='columns')
final

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [47]:
result = final.drop(['town','west windsor'],axis='columns')
result.head(3)

area   price  monroe township  robinsville
0  2600  550000                1            0
1  3000  565000                1            0
2  3200  610000                1            0

In [48]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [49]:
X = result.drop(['price'],axis='columns')
X.head(3)

area  monroe township  robinsville
0  2600                1            0
1  3000                1            0
2  3200                1            0

In [50]:
y = result['price']

In [51]:
model.fit(X,y)

LinearRegression()

In [53]:
model.predict([[2800,0,1]])

array([590775.63964739])

In [54]:
model.predict([[3400,0,0]])

array([681241.66845839])

In [72]:
model.score(X,y)

0.9573929037221871

### --------- Assignment ----------

1) Predict price of a mercedez benz that is 4 yr old with mileage 45000

2) Predict price of a BMW X5 that is 7 yr old with mileage 86000

3) Tell me the score (accuracy) of your model. (Hint: use LinearRegression().score())

In [75]:
df1 = pd.read_csv('Exercise/carprices.csv')
df1

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [83]:
dum = pd.get_dummies(df1['Car Model'])
dum

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [99]:
befo_final = pd.concat([df1,dum],axis='columns')
befo_final

Car Model  Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  \
0                  BMW X5    69000          18000         6        0       1   
1                  BMW X5    35000          34000         3        0       1   
2                  BMW X5    57000          26100         5        0       1   
3                  BMW X5    22500          40000         2        0       1   
4                  BMW X5    46000          31500         4        0       1   
5                 Audi A5    59000          29400         5        1       0   
6                 Audi A5    52000          32000         5        1       0   
7                 Audi A5    72000          19300         6        1       0   
8                 Audi A5    91000          12000         8        1       0   
9   Mercedez Benz C class    67000          22000         6        0       0   
10  Mercedez Benz C class    83000          20000         7        0       0   
11  Mercedez Benz C class    79000          21000         7        0       0   
12  Mercedez Benz C class    59000          33000         5        0       0   

    Mercedez Benz C class  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0  
5                       0  
6                       0  
7                       0  
8                       0  
9                       1  
10                      1  
11                      1  
12                      1

In [89]:
fin_result = befo_final.drop(['Car Model','Mercedez Benz C class'],axis='columns')
fin_result

Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6        0       1
1     35000          34000         3        0       1
2     57000          26100         5        0       1
3     22500          40000         2        0       1
4     46000          31500         4        0       1
5     59000          29400         5        1       0
6     52000          32000         5        1       0
7     72000          19300         6        1       0
8     91000          12000         8        1       0
9     67000          22000         6        0       0
10    83000          20000         7        0       0
11    79000          21000         7        0       0
12    59000          33000         5        0       0

In [90]:
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()

In [92]:
X1 = fin_result.drop(['Sell Price($)'],axis='columns')

In [94]:
y1 = fin_result['Sell Price($)']

In [96]:
model1.fit(X1,y1)

LinearRegression()

In [103]:
model1.predict([[45000,4,0,0]])

array([36991.31721061])

In [106]:
model1.predict([[86000,7,0,1]])

array([11080.74313219])

In [105]:
model1.score(X1,y1)

0.9417050937281082