In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [30]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [31]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [18]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

### Data preprocessing step is OVER

In [20]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price) # this is for train our model

LinearRegression()

In [22]:
reg.coef_   # M1 , M2 , M3 this is we got output

array([  112.06244194, 23388.88007794, -3231.71790863])

In [23]:
reg.intercept_

221323.00186540384

### 3000 sqr. ft area, 3 bedrooms, 40 years old

In [28]:
reg.predict([[3000,3,40]])

array([498408.25158031])

### 2500 sqr. ft area, 4 bedrooms, 5 years old

In [25]:
reg.predict([[2500,4,5]])

array([578876.03748933])

#### coef1*area + coef2*bedrooms + coef3*age + intercept

In [30]:
112.06244194 * 3000 +23388.88007794*3 + -3231.71790863*40 + 221323.00186540384

498408.25157402386

In [31]:
112.06244194 * 2500 +23388.88007794*4 + -3231.71790863*5 + 221323.00186540384

578876.0374840139

# Assignment

### Q-1. 2yr experience, 9 test score, 6 interview score

### Q-2. 12yr experience, 10 test score, 10 interview score

In [9]:
!pip install word2number

  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5586 sha256=be4256967c7916ef4ed6cb240cade54408e79fa674a49e2f09b9c2dcd76ddcf1
  Stored in directory: c:\users\kisho\appdata\local\pip\cache\wheels\cb\f3\5a\d88198fdeb46781ddd7e7f2653061af83e7adb2a076d8886d6
Successfully built word2number


In [41]:
from word2number import w2n

print(w2n.word_to_num('point one'))

0.1


In [54]:
df1 = pd.read_csv('hiring.csv')
df1

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [56]:
df1.experience = df1.experience.fillna('zero')
df1

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [57]:
from word2number import w2n

df1.experience = df1.experience.apply(w2n.word_to_num)

In [58]:
df1

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [59]:
median_test_score = math.floor(df1.test_score.median())
median_test_score

8

In [60]:
df1.test_score = df1.test_score.fillna(median_test_score)
df1

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [62]:
reg1 = linear_model.LinearRegression()
reg1.fit(df1[['experience','test_score','interview_score']],df1.salary)

LinearRegression()

In [63]:
reg1.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [64]:
reg1.intercept_

17737.263464337688

In [65]:
reg1.predict([[2,9,6]])

array([53205.96797671])

In [66]:
reg1.predict([[12,10,10]])

array([92002.18340611])

In [67]:
2812.95487627*2 + 1845.70596798*9 + 2205.24017467*6 + 17737.263464337688

53205.96797671769

In [68]:
2812.95487627*12 + 1845.70596798*10 + 2205.24017467*10 + 17737.263464337688

92002.18340607767